ESSENTIALS=(
    sudo
    git
    base-devel
    networkmanager
    vim
    less
    openssh
    nm-connection-editor
    man-db
    man-pages
    curl
    reflector
    zsh
)

AUDIO_DRIVERS=(
    alsa-utils
    pipewire
    pipewire-alsa
    pipewire-pulse
    pipewire-jack
    wireplumber
)

BT_DRIVERS=(
    bluez
    bluez-utils
    pipewire-audio
)

WEBCAM_DRIVERS=(
    v4l-utils
)

#PRINTER_DRIVERS=(
    #cups
    #sane
#)

INTEL_GPU_DRIVERS=(
    mesa
    vulkan-intel
    lbva-intel-driver
)

AMD_GPU_DRIVERS=(
    mesa
    vulkan-radeon
    libva-mesa-driver
)

NVIDIA_GPU_DRIVERS=(
    nvidia
    nvidia-utils
    nvidia-settings
)

HYPRLAND=(
    hyprland
    xorg-xwayland
    wayland-protocols
    wl-clipboard
    xdg-desktop-portal
    xdg-desktop-portal-wlr
    xwaylandvideobridge
    waybar
    swaync
    hypridle
    hyprlock
    hyprshot
    wofi
    swww
    kitty
    nerd-fonts-fira-code
)

LAPTOP=(
    tlp
    acpi
    upower
    brightnessctl
    rfkill
)

SYSTEM_UTILS=(
  btop
  stow
  neofetch
  fzf
  zip
  unzip
  curl
  zoxide
  flatpak
  figlet
)

# Development tools
DEV_TOOLS=(
  bat
  git-delta
  docker
  docker-compose
  tree
  visual-studio-code-bin
)

APPLICATIONS=(
  firefox
  parsec-bin
  tailscale
  ttysvr
)