ESSENTIALS=(
    sudo
    git
    base-devel
    networkmanager
    vim
    less
    openssh
    nm-connection-editor
    man-db
    man-pages
    curl
    reflector
)

AUDIO_DRIVERS=(
    alsa-utils
    pipewire
    pipewire-alsa
    pipewire-pulse
    pipewire-jack
    wireplumber
)

BT_DRIVERS=(
    bluez
    bluez-utils
    pipewire-audio
)

WEBCAM_DRIVERS=(
    v4l-utils
)

#PRINTER_DRIVERS=(
    #cups
    #sane
#)

INTEL_GPU_DRIVERS=(
    mesa
    vulkan-intel
    lbva-intel-driver
)

AMD_GPU_DRIVERS=(
    mesa
    vulkan-radeon
    libva-mesa-driver
)

NVIDIA_GPU_DRIVERS=(
    nvidia
    nvidia-utils
    nvidia-settings
)

HYPRLAND=(
    xorg-xwayland
)

LAPTOP=(
    tlp
    acpi
    upower
    brightnessctl
    rfkill
)
